[package]
name = "TerminalMediaPlayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
gif = "0.11.4"
rgb = "0.8"
ansi_rgb = "0.2.0"
