[package]
name = "TerminalMediaPlayer"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.2"
eventual = "0.1.7"
dirs = "4.0.0"
rodio = "0.15.0"
crossterm = "0.25.0"
lazy_static = "1.4.0"
timer = "0.2.0"
chrono = "0.4.22"